### ISSUE TITLE
Really nice project! Which your nears goals? You need help?

### ISSUE THREAD

**Issue by ryukinix** [PyroAVR/Mega-Man-Reassembled#2]
: D MegaMan is love. I think would really nice see this working. Congratulations for the start and using Python!

Sadly I try running some files, but I have some problems at `/tests` files. Doesn't working fine here, I try fix the first errors, but then did appears more and more.

The src/ files is really on beginning, right? I see only the menu.

If you need some help, would be great help you! I see some problemas with python standards, as files names. I maybe can help you doing review at that, such .pyc files should not be in the repo also.

Manoel.

**Comment by PyroAVR** [comment]
Manoel, 
Thank you so much for your interest in our project! I honestly didn't think anyone would notice it.  Nothing really runs at the moment, actually. We're just starting out.  I am a C++ programmer, and my colleague is a Java programmer, so we're using Python as a middle ground, as neither of us really want to delve into the other's native language.  
My apologies for the rather disorganized structure and lack of documentation, we haven't gotten around to all of that just yet, again, neither of us are game programmers, so we're learning as we go what works best for us.
**Here's a quick layout for you:**
- `/src`
 - This directory is where all the working code will go.  It's rather empty because much of our code is just figuring out how everything is going to fit together.
 - Python code will go here, as well as any necessary C/C++ extensions that we have to write.

- `/test`
 - This is where we work on new things that aren't already started in the `/src` directory. 
 - For example, I might work on a Tiled Map Editor extension in that directory, and then make it a folder in `/src` when it's more than just testing and figuring out what goes where.

- `/assets`
 - This is where all the requisite media will go.  Spritesheets, music, level files, etc.  Currently, the structure for it is messy as our game code is non-functional and we're designing the very basics.

- `/docs`
 - Pretty self-explanatory, documentation.  It is noticeably lacking, but again, that's because there's not much to document just yet.

**The Future**
We have a few goals set, and some imagination for what the future will be like for Mega Man: Reassembled. Here's the basics:
*Goals*
- Working, efficient, easy to use and understand game logic.  This is really the first step, except that is requires the following steps to fulfill the efficient and easy to use guidelines
- Automatic level loading, streamlining and standardization of all sorts of back-end related tasks
- UI design
- Media creation/acquisition and level creation.  Once we get everything working, we'll drop the "developer levels" and get real textures, levels, scenes, etc.

*Guidelines*
- Fully extensible: We want MM:R to be easily extended by players without difficulty.  This requires a level builder interface.
- Fun:  Difficult, a la Mega man, but not impossible.
- Story-Driven:  Most Mega man games lack a decent storyline, character development, etc.  I think this is very important for us, MM:R should be different from the canon in that sense.


There's plenty more to come, but we're still planning.  With luck, we'll really get somewhere with this!

**Comment by ryukinix** [comment]
Mega Man is always notable! If I can, I really wish support you! I only was exploring some projects about plataformers' using Python and I found that. Really nice! I expect that project cloud be something big!

My native language is Python and as my regards with your project, I pushed the #4. 

Good luck!
